name: k8s-deployment-webserver

on:
  push:
    branches:
      - "master"
    paths:
      - "k8s/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4